DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS department;



CREATE TABLE department (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  dep_name VARCHAR(30) NOT NULL
);

CREATE TABLE role (
  id INTEGER AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL(10, 2) NOT NULL,
  department_id INTEGER,
  CONSTRAINT fk_department fOREIGN KEY (department_id) REFERENCES department(id) ON DELETE SET NULL
);



